import type { ColumnInfo } from '@common/types'
import { Button } from '@renderer/components/ui/button'
import { Input } from '@renderer/components/ui/input'
import { Label } from '@renderer/components/ui/label'
import { Popover, PopoverContent, PopoverTrigger } from '@renderer/components/ui/popover'
import { Sheet, SheetContent, SheetFooter, SheetTitle } from '@renderer/components/ui/sheet'
import { cn } from '@renderer/lib/utils'
import { format } from 'date-fns'
import { CalendarIcon } from 'lucide-react'
import { useState } from 'react'

interface AddRowDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  columns: ColumnInfo[]
  onSubmit: (values: Record<string, unknown>) => void
  isPending?: boolean
  tableName?: string
}

export function AddRowDialog({
  open,
  onOpenChange,
  columns,
  onSubmit,
  isPending,
  tableName
}: AddRowDialogProps) {
  const [values, setValues] = useState<Record<string, string>>({})

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    // Convert values to appropriate types
    const processedValues: Record<string, unknown> = {}
    for (const column of columns) {
      const value = values[column.name]

      // Skip auto-generated columns
      if (
        column.defaultValue?.toString().includes('IDENTITY') ||
        column.defaultValue?.toString().includes('SERIAL')
      ) {
        continue
      }

      // Handle empty values
      if (value === '' || value === undefined) {
        processedValues[column.name] = column.nullable ? null : ''
        continue
      }

      // Type conversion based on column type
      const type = column.type.toLowerCase()
      try {
        if (type.includes('int') || type.includes('serial')) {
          const num = parseInt(value, 10)
          if (isNaN(num)) {
            throw new Error(`Invalid integer value for ${column.name}`)
          }
          processedValues[column.name] = num
        } else if (
          type.includes('float') ||
          type.includes('double') ||
          type.includes('numeric') ||
          type.includes('decimal')
        ) {
          const num = parseFloat(value)
          if (isNaN(num)) {
            throw new Error(`Invalid numeric value for ${column.name}`)
          }
          processedValues[column.name] = num
        } else if (type.includes('bool') || type.includes('boolean')) {
          processedValues[column.name] =
            value.toLowerCase() === 'true' || value === '1' || value.toLowerCase() === 'yes'
        } else if (
          type.includes('timestamp') ||
          type.includes('datetime') ||
          type.includes('date')
        ) {
          // For timestamp/date fields, convert to ISO string
          const date = new Date(value)
          if (isNaN(date.getTime())) {
            throw new Error(`Invalid date value for ${column.name}`)
          }
          processedValues[column.name] = date.toISOString()
        } else if (type.includes('json')) {
          // For JSON fields, try to parse as JSON
          try {
            processedValues[column.name] = JSON.parse(value)
          } catch {
            // If not valid JSON, store as string
            processedValues[column.name] = value
          }
        } else {
          processedValues[column.name] = value
        }
      } catch (error) {
        const errorMsg = error instanceof Error ? error.message : 'Unknown error'
        throw new Error(`Error processing ${column.name}: ${errorMsg}`)
      }
    }

    onSubmit(processedValues)
  }

  const handleValueChange = (columnName: string, value: string) => {
    setValues((prev) => ({ ...prev, [columnName]: value }))
  }

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-full sm:max-w-2xl [&>button]:hidden gap-0">
        <SheetTitle>
          <div className="flex items-center justify-between border-b px-6 py-4">
            <h2 className="text-lg font-semibold">
              {tableName ? `Add row to ${tableName}` : 'Add New Row'}
            </h2>
          </div>
        </SheetTitle>
        {/* Scrollable section like table-drawer */}
        <div className="relative flex-1 overflow-y-auto">
          <div className="flex flex-col gap-3 px-6 pt-6">
            {columns
            .filter((column) => column.name !== 'id')
            .map((column) => {
              const isAutoGenerated =
                column.defaultValue?.toString().includes('IDENTITY') ||
                column.defaultValue?.toString().includes('SERIAL')
              const isTimestamp =
                column.type.toLowerCase().includes('timestamp') ||
                column.type.toLowerCase().includes('datetime')

              return (
                <div
                  key={column.name}
                  className="flex flex-col gap-1.5 rounded-md border border-border bg-muted/30 p-2.5"
                >
                  <Label
                    htmlFor={column.name}
                    className="text-sm font-medium flex justify-between items-center"
                  >
                    <span>
                      {column.name}
                      {!column.nullable && !isAutoGenerated && (
                        <span className="text-destructive ml-1">*</span>
                      )}
                    </span>
                    <span className="text-muted-foreground text-xs">
                      {column.type}
                      {column.defaultValue ? (
                        <span className="ml-1">
                          |{' Default: '}
                          {typeof column.defaultValue === 'string'
                            ? column.defaultValue
                            : JSON.stringify(column.defaultValue)}
                        </span>
                      ) : null}
                    </span>
                  </Label>
                  <div className="flex flex-col gap-1.5">
                    {isAutoGenerated ? (
                      <Input
                        id={column.name}
                        value="Auto-generated"
                        disabled
                        className="bg-muted h-9 transition-all border-border focus:border-white! focus-visible:border-white! focus-visible:ring-0 focus-visible:ring-offset-0 focus:ring-0 focus:ring-offset-0"
                      />
                    ) : isTimestamp ? (
                      <Popover>
                        <PopoverTrigger asChild>
                          <Button
                            variant="outline"
                            className={cn(
                              'w-full justify-start text-left font-normal h-9',
                              !values[column.name] && 'text-muted-foreground'
                            )}
                          >
                            <CalendarIcon className="mr-2 h-4 w-4" />
                            {values[column.name] ? (
                              format(new Date(values[column.name]), 'PPP HH:mm')
                            ) : (
                              <span>Pick a date and time</span>
                            )}
                          </Button>
                        </PopoverTrigger>
                        <PopoverContent className="w-auto p-4" align="start">
                          <Input
                            type="datetime-local"
                            value={values[column.name] || ''}
                            onChange={(e) => handleValueChange(column.name, e.target.value)}
                            className="w-full transition-all border-border focus:border-white! focus-visible:border-white! focus-visible:ring-0 focus-visible:ring-offset-0 focus:ring-0 focus:ring-offset-0"
                          />
                          <div className="flex gap-2 mt-2">
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => {
                                const now = new Date()
                                const localDateTime = format(now, "yyyy-MM-dd'T'HH:mm")
                                handleValueChange(column.name, localDateTime)
                              }}
                              className="flex-1"
                            >
                              Now
                            </Button>
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => handleValueChange(column.name, '')}
                              className="flex-1"
                            >
                              Clear
                            </Button>
                          </div>
                        </PopoverContent>
                      </Popover>
                    ) : (
                      <Input
                        id={column.name}
                        value={values[column.name] || ''}
                        onChange={(e) => handleValueChange(column.name, e.target.value)}
                        placeholder={column.nullable ? 'Optional' : 'Required'}
                        required={!column.nullable}
                        className="h-9 transition-all border-border focus:border-white! focus-visible:border-white! focus-visible:ring-0 focus-visible:ring-offset-0 focus:ring-0 focus:ring-offset-0"
                      />
                    )}
                  </div>
                </div>
              )
            })}
          </div>
          {/* Bottom fade anchored to footer's top border */}
          <div
            aria-hidden
            className="pointer-events-none sticky bottom-0 z-10 h-14 w-full bg-linear-to-b from-background/0 via-background/70 to-background"
          />
        </div>

        <SheetFooter className="flex flex-row items-center justify-end gap-2 border-t p-4">
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => onOpenChange(false)}
            disabled={isPending}
          >
            Cancel
          </Button>
          <Button type="submit" disabled={isPending} onClick={handleSubmit} size="sm">
            {isPending ? 'Adding...' : 'Add Row'}
          </Button>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  )
}
