import type { ColumnInfo } from '@common/types'
import { Button } from '@renderer/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from '@renderer/components/ui/dialog'
import { Input } from '@renderer/components/ui/input'
import { Label } from '@renderer/components/ui/label'
import { Popover, PopoverContent, PopoverTrigger } from '@renderer/components/ui/popover'
import { cn } from '@renderer/lib/utils'
import { format } from 'date-fns'
import { CalendarIcon } from 'lucide-react'
import { useState } from 'react'

interface AddRowDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  columns: ColumnInfo[]
  onSubmit: (values: Record<string, unknown>) => void
  isPending?: boolean
}

export function AddRowDialog({
  open,
  onOpenChange,
  columns,
  onSubmit,
  isPending
}: AddRowDialogProps) {
  const [values, setValues] = useState<Record<string, string>>({})

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    // Convert values to appropriate types
    const processedValues: Record<string, unknown> = {}
    for (const column of columns) {
      const value = values[column.name]

      // Skip auto-generated columns
      if (column.defaultValue?.toString().includes('IDENTITY') || column.defaultValue?.toString().includes('SERIAL')) {
        continue
      }

      // Handle empty values
      if (value === '' || value === undefined) {
        processedValues[column.name] = column.nullable ? null : ''
        continue
      }

      // Type conversion based on column type
      const type = column.type.toLowerCase()
      if (type.includes('int') || type.includes('serial')) {
        processedValues[column.name] = parseInt(value, 10)
      } else if (type.includes('float') || type.includes('double') || type.includes('numeric')) {
        processedValues[column.name] = parseFloat(value)
      } else if (type.includes('bool')) {
        processedValues[column.name] = value.toLowerCase() === 'true' || value === '1'
      } else if (type.includes('timestamp') || type.includes('datetime')) {
        // For timestamp fields, convert to ISO string
        processedValues[column.name] = value ? new Date(value).toISOString() : null
      } else {
        processedValues[column.name] = value
      }
    }

    onSubmit(processedValues)
  }

  const handleValueChange = (columnName: string, value: string) => {
    setValues((prev) => ({ ...prev, [columnName]: value }))
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-[60vw]! w-[60vw]! h-[85vh] flex flex-col" style={{ maxWidth: '90vw', width: '90vw' }}>
        <DialogHeader>
          <DialogTitle>Add New Row</DialogTitle>
          <DialogDescription>Fill in the values for the new row</DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="flex flex-col flex-1 min-h-0">
          <div className="space-y-4 py-4 pr-4 overflow-y-auto flex-1">
            {columns.map((column) => {
              const isAutoGenerated =
                column.defaultValue?.toString().includes('IDENTITY') || column.defaultValue?.toString().includes('SERIAL')
              const isTimestamp = column.type.toLowerCase().includes('timestamp') ||
                                 column.type.toLowerCase().includes('datetime')

              return (
                <div key={column.name} className="grid grid-cols-3 items-center gap-6">
                  <Label htmlFor={column.name} className="text-right">
                    {column.name}
                    {!column.nullable && !isAutoGenerated && (
                      <span className="text-destructive ml-1">*</span>
                    )}
                  </Label>
                  <div className="col-span-2">
                    {isAutoGenerated ? (
                      <Input
                        id={column.name}
                        value="Auto-generated"
                        disabled
                        className="bg-muted"
                      />
                    ) : isTimestamp ? (
                      <Popover>
                        <PopoverTrigger asChild>
                          <Button
                            variant="outline"
                            className={cn(
                              'w-full justify-start text-left font-normal',
                              !values[column.name] && 'text-muted-foreground'
                            )}
                          >
                            <CalendarIcon className="mr-2 h-4 w-4" />
                            {values[column.name] ? (
                              format(new Date(values[column.name]), 'PPP HH:mm')
                            ) : (
                              <span>Pick a date and time</span>
                            )}
                          </Button>
                        </PopoverTrigger>
                        <PopoverContent className="w-auto p-4" align="start">
                          <Input
                            type="datetime-local"
                            value={values[column.name] || ''}
                            onChange={(e) => handleValueChange(column.name, e.target.value)}
                            className="w-full"
                          />
                          <div className="flex gap-2 mt-2">
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => {
                                const now = new Date()
                                const localDateTime = format(now, "yyyy-MM-dd'T'HH:mm")
                                handleValueChange(column.name, localDateTime)
                              }}
                              className="flex-1"
                            >
                              Now
                            </Button>
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => handleValueChange(column.name, '')}
                              className="flex-1"
                            >
                              Clear
                            </Button>
                          </div>
                        </PopoverContent>
                      </Popover>
                    ) : (
                      <Input
                        id={column.name}
                        value={values[column.name] || ''}
                        onChange={(e) => handleValueChange(column.name, e.target.value)}
                        placeholder={
                          column.nullable
                            ? `${column.type} (nullable)`
                            : `${column.type} (required)`
                        }
                        required={!column.nullable}
                      />
                    )}
                    <p className="text-xs text-muted-foreground mt-1">
                      {`Type: ${column.type}${column.defaultValue ? ` | Default: ${String(column.defaultValue)}` : ''}`}
                    </p>
                  </div>
                </div>
              )
            })}
          </div>
          <DialogFooter className="mt-4 pt-4 border-t">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={isPending}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={isPending}>
              {isPending ? 'Adding...' : 'Add Row'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
