import { language as pgsqlLanguage } from 'monaco-sql-languages/esm/languages/pgsql/pgsql'

const CURATED_SQL_KEYWORDS = [
  'SELECT DISTINCT',
  'SELECT',
  'FROM',
  'WHERE',
  'INNER JOIN',
  'LEFT JOIN',
  'RIGHT JOIN',
  'FULL OUTER JOIN',
  'CROSS JOIN',
  'JOIN',
  'ON',
  'GROUP BY',
  'ORDER BY',
  'HAVING',
  'LIMIT',
  'OFFSET',
  'UNION ALL',
  'UNION',
  'INTERSECT',
  'EXCEPT',
  'INSERT INTO',
  'VALUES',
  'UPDATE',
  'SET',
  'DELETE FROM',
  'DELETE',
  'RETURNING',
  'CREATE TABLE IF NOT EXISTS',
  'CREATE TABLE',
  'CREATE INDEX',
  'CREATE OR REPLACE VIEW',
  'CREATE VIEW',
  'ALTER TABLE',
  'DROP TABLE IF EXISTS',
  'DROP TABLE',
  'TRUNCATE TABLE',
  'WITH',
  'AS',
  'AND',
  'OR',
  'NOT',
  'NULL',
  'IS NULL',
  'IS NOT NULL',
  'TRUE',
  'FALSE',
  'DISTINCT',
  'IN',
  'LIKE',
  'ILIKE',
  'BETWEEN',
  'EXISTS',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'ASC',
  'DESC',
  'COUNT(*)',
  'COALESCE',
  'NULLIF',
  'PRIMARY KEY',
  'FOREIGN KEY',
  'REFERENCES',
  'DEFAULT',
  'DEFERRABLE',
  'DEFERRED',
  'CHECK',
  'UNIQUE',
  'CASCADE',
  'BEGIN',
  'COMMIT',
  'ROLLBACK'
]

const pgsqlKeywords = Array.isArray(pgsqlLanguage.keywords)
  ? pgsqlLanguage.keywords.filter((keyword): keyword is string => typeof keyword === 'string')
  : []

export const SQL_COMPLETION_KEYWORDS = Array.from(
  new Set([...CURATED_SQL_KEYWORDS, ...pgsqlKeywords])
)
